graph_file_path: "/opt/movidius/ncappzoo/tensorflow/inception_v2/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/imagenet1001.txt"
network_dimension: 224
channel1_mean: 128
channel2_mean: 128
channel3_mean: 128
scale: 0.0078125 
